#ifndef IHW_SORTING_LGORITHMS_TESTING_MERGE_SORT_H
#define IHW_SORTING_LGORITHMS_TESTING_MERGE_SORT_H
#include "vector"

void mergeSort(std::vector<int> &array);

#endif  // IHW_SORTING_LGORITHMS_TESTING_MERGE_SORT_H
