#ifndef IHW_SORTING_LGORITHMS_TESTING_REGULAR_AND_BINARY_INSERTION_SORT_H
#define IHW_SORTING_LGORITHMS_TESTING_REGULAR_AND_BINARY_INSERTION_SORT_H

void regularInsertionSort(std::vector<int>& arr);

void binaryInsertionSort(std::vector<int>& arr);

#endif  // IHW_SORTING_LGORITHMS_TESTING_REGULAR_AND_BINARY_INSERTION_SORT_H
